# -*- coding: utf-8 -*-
"""Auction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12RmkCXVgh09UPaDqDKD3H0VkvCTXbwfV
"""

import pandas as pd

file_path = "/content/ipl_auction_tables_3_to_10.xlsx"

data_types = {
    'Player': str,
    'Nationality': str,
    'Type': str,
    'Price Paid': float
}

df = pd.read_excel(file_path, dtype=data_types)

print(df.dtypes)
print(df)

df.rename(columns={'Source Table': 'Team Name'}, inplace=True)

table_replacements = {
    'Table 3': 'Delhi Capitals',
    'Table 4': 'Gujarat Titans',
    'Table 5': 'Kolkata Knight Riders',
    'Table 6': 'Lucknow Super Giants',
    'Table 7': 'Mumbai Indians',
    'Table 8': 'Punjab Kings',
    'Table 9': 'Rajasthan Royals',
    'Table 10': 'Royal Challengers Bangalore',
    'Table 11': 'Sunrisers Hyderabad'
}

df['Team Name'] = df['Team Name'].replace(table_replacements)

df.to_excel(file_path, index=False)



print("Team names updated and saved successfully.")
print(df)



rows_51_to_60 = df.iloc[50:60]